# InfraOwl Model Training Configuration

model:
  architecture: "efficientnet_lite0"  # Options: efficientnet_lite0, mobilenetv3_small, custom_cnn
  input_size: [224, 224, 3]
  num_classes: 5  # Update based on your infrastructure issue types
  weights: "imagenet"  # Pre-trained weights for transfer learning
  
training:
  epochs: 50
  batch_size: 32
  learning_rate: 0.001
  optimizer: "adam"
  loss_function: "categorical_crossentropy"
  metrics: ["accuracy", "top_2_accuracy"]
  
  # Learning rate schedule
  lr_schedule:
    type: "reduce_on_plateau"  # Options: reduce_on_plateau, exponential_decay, cosine_decay
    factor: 0.5
    patience: 5
    min_lr: 0.00001
  
  # Early stopping
  early_stopping:
    monitor: "val_accuracy"
    patience: 10
    restore_best_weights: true

data:
  train_split: 0.7
  val_split: 0.2
  test_split: 0.1
  
  # Data augmentation
  augmentation:
    enabled: true
    rotation_range: 20
    width_shift_range: 0.2
    height_shift_range: 0.2
    shear_range: 0.2
    zoom_range: 0.2
    horizontal_flip: true
    brightness_range: [0.8, 1.2]
    
  # Preprocessing
  preprocessing:
    rescale: 0.00392156862745098  # 1/255
    target_size: [224, 224]
    color_mode: "rgb"

# TensorFlow Lite conversion settings
tflite:
  quantization:
    enabled: true
    type: "dynamic"  # Options: dynamic, int8, float16
  optimization:
    - "DEFAULT"
    - "OPTIMIZE_FOR_SIZE"
  
# Infrastructure issue classes
classes:
  - "pothole"
  - "crack"
  - "broken_pipe" 
  - "damaged_road"
  - "normal"

# Paths
paths:
  raw_data: "data/raw_images"
  processed_data: "data/processed"
  models: "models"
  logs: "logs"
  outputs: "outputs"

# Monitoring and logging
logging:
  level: "INFO"
  tensorboard: true
  save_model_summary: true
  plot_training_history: true